package org.mlpiper.mlops


/** TODO: make this constants to be autogenerated in reflex-common
  * for Python, Java, Scala */
object MLOpsEnvConstants extends Enumeration {

  type MLOpsEnvConstants = Value

  val MLOPS_MODE: MLOpsEnvConstants.Value = Value("PM_MLOPS_MODE")

  val MLOPS_OUTPUT_CHANNEL: MLOpsEnvConstants.Value = Value("PM_MLOPS_OUTPUT_CHANNEL")

  val PM_MLOPS_FILE: MLOpsEnvConstants.Value = Value("PM_MLOPS_FILE")

  val REST_SERVER_PORT: MLOpsEnvConstants.Value = Value("PM_MLOPS_REST_SERVER_PORT")
  val REST_SERVER_WAIT_FOR_EXIT: MLOpsEnvConstants.Value = Value("PM_REST_SERVER_WAIT_FOR_EXIT")

  val MLOPS_TIMESERIES_DB_HOST: MLOpsEnvConstants.Value = Value("PM_TIMESERIES_DB_HOST")
  val MLOPS_TIMESERIES_DB_PORT: MLOpsEnvConstants.Value = Value("PM_TIMESERIES_DB_PORT")

  val MLOPS_ION_ID: MLOpsEnvConstants.Value = Value("PM_WORKFLOW_INSTANCE_ID")
  val MLOPS_PIPELINE_ID: MLOpsEnvConstants.Value = Value("PM_PIPELINE_INSTANCE_ID")
  val MLOPS_ION_NODE_ID: MLOpsEnvConstants.Value = Value("PM_WORKFLOW_NODE_ID")

  val MLOPS_ZK_HOST: MLOpsEnvConstants.Value = Value("PM_ZK_HOST")
  val MLOPS_TOKEN: MLOpsEnvConstants.Value = Value("PM_MLOPS_USER_TOKEN")

  val MLOPS_ML_OBJECT_SERVER_HOST: MLOpsEnvConstants.Value = Value("ML_OBJECT_SERVER_HOST")
  val MLOPS_ML_OBJECT_SERVER_PORT: MLOpsEnvConstants.Value = Value("ML_OBJECT_SERVER_PORT")

  val MLOPS_AGENT_PUBLIC_ADDRESS: MLOpsEnvConstants.Value = Value("AGENT_PUBLIC_ADDRESS")

  val MLOPS_DATA_REST_SERVER: MLOpsEnvConstants.Value = Value("PM_MLOPS_DATA_REST_SERVER")
  val MLOPS_DATA_REST_PORT: MLOpsEnvConstants.Value = Value("PM_MLOPS_DATA_REST_PORT")

  val MLOPS_MODEL_ID: MLOpsEnvConstants.Value = Value("PM_MLOPS_MODEL_ID")

  val MLOPS_PRODUCER_MODEL_ID: MLOpsEnvConstants.Value = Value("PM_PRODUCER_MLOPS_MODEL_ID")
}
