# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mcenter_server_api.models.base_model_ import Model
from mcenter_server_api import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sandbox_alerts=None, production_alerts=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param sandbox_alerts: The sandbox_alerts of this InlineResponse200.  # noqa: E501
        :type sandbox_alerts: List[List[Event]]
        :param production_alerts: The production_alerts of this InlineResponse200.  # noqa: E501
        :type production_alerts: List[List[Event]]
        """
        self.openapi_types = {
            'sandbox_alerts': 'List[List[Event]]',
            'production_alerts': 'List[List[Event]]'
        }

        self.attribute_map = {
            'sandbox_alerts': 'sandboxAlerts',
            'production_alerts': 'productionAlerts'
        }

        self._sandbox_alerts = sandbox_alerts
        self._production_alerts = production_alerts

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sandbox_alerts(self):
        """Gets the sandbox_alerts of this InlineResponse200.


        :return: The sandbox_alerts of this InlineResponse200.
        :rtype: List[List[Event]]
        """
        return self._sandbox_alerts

    @sandbox_alerts.setter
    def sandbox_alerts(self, sandbox_alerts):
        """Sets the sandbox_alerts of this InlineResponse200.


        :param sandbox_alerts: The sandbox_alerts of this InlineResponse200.
        :type sandbox_alerts: List[List[Event]]
        """

        self._sandbox_alerts = sandbox_alerts

    @property
    def production_alerts(self):
        """Gets the production_alerts of this InlineResponse200.


        :return: The production_alerts of this InlineResponse200.
        :rtype: List[List[Event]]
        """
        return self._production_alerts

    @production_alerts.setter
    def production_alerts(self, production_alerts):
        """Sets the production_alerts of this InlineResponse200.


        :param production_alerts: The production_alerts of this InlineResponse200.
        :type production_alerts: List[List[Event]]
        """

        self._production_alerts = production_alerts
