# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mcenter_server_api.models.base_model_ import Model
from mcenter_server_api import util


class ModelUsageUsageTimes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start=None, end=None):  # noqa: E501
        """ModelUsageUsageTimes - a model defined in OpenAPI

        :param start: The start of this ModelUsageUsageTimes.  # noqa: E501
        :type start: int
        :param end: The end of this ModelUsageUsageTimes.  # noqa: E501
        :type end: int
        """
        self.openapi_types = {
            'start': 'int',
            'end': 'int'
        }

        self.attribute_map = {
            'start': 'start',
            'end': 'end'
        }

        self._start = start
        self._end = end

    @classmethod
    def from_dict(cls, dikt) -> 'ModelUsageUsageTimes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelUsage_usageTimes of this ModelUsageUsageTimes.  # noqa: E501
        :rtype: ModelUsageUsageTimes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self):
        """Gets the start of this ModelUsageUsageTimes.


        :return: The start of this ModelUsageUsageTimes.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this ModelUsageUsageTimes.


        :param start: The start of this ModelUsageUsageTimes.
        :type start: int
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this ModelUsageUsageTimes.


        :return: The end of this ModelUsageUsageTimes.
        :rtype: int
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this ModelUsageUsageTimes.


        :param end: The end of this ModelUsageUsageTimes.
        :type end: int
        """

        self._end = end
