
# Constants to access pipeline json fields
PIPELINE_NAME_FIELD = 'name'
PIPELINE_ENGINE_TYPE_FIELD = 'engineType'
PIPELINE_LANGUAGE_FIELD = 'language'
PIPELINE_SYSTEM_CONFIG_FIELD = 'systemConfig'
PIPELINE_PIPE_FIELD = 'pipe'
PIPELINE_COMP_ID_FIELD = 'id'
PIPELINE_COMP_TYPE_FIELD = 'type'
PIPELINE_COMP_ARGUMENTS_FIELD = 'arguments'
PIPELINE_COMP_PARENTS_FIELD = 'parents'
PIPELINE_COMP_PARENTS_FIRST_FIELD = 'parent'
PIPELINE_COMP_PARENTS_SECOND_FIELD = 'output'

# Constants to access component description json fields
COMPONENT_DESC_NAME_FIELD = 'name'
COMPONENT_DESC_PROGRAM_FIELD = 'program'
COMPONENT_DESC_LANGUAGE_FIELD = "language"
COMPONENT_DESC_DESCRIPTION_FIELD = "description"
COMPONENT_DESC_CLASS_FIELD = 'componentClass'
COMPONENT_DESC_ARGUMENTS = 'arguments'
COMPONENT_DESC_ARGUMENT_KEY = 'key'
COMPONENT_DESC_ARGUMENT_TAG = 'tag'
COMPONENT_DESC_ARGUMENT_DEFAULT_VAL = 'defaultValue'
COMPONENT_DESC_ARGUMENT_ENV_VAR = 'envVar'
COMPONENT_DESC_USER_STAND_ALONE = "userStandalone"
COMPONENT_DESC_PYTHON_DEPS = 'deps'

# Auto-generated internal fields
COMPONENT_DESC_PACKAGE_FIELD = 'package'

# Component metadata reference json
COMPONENT_METADATA_REF_FILE_NAME_FIELD = 'metadataFilename'
