import time
import datetime
import abc

from drycode.dry_defs import DryDefs


class CodeBuilderBase:
    def __init__(self):
        self._add_time_stamp = True

    def add_time_stamp(self, add_time_stamp=True):
        self._add_time_stamp = add_time_stamp
        return self

    def get_auto_gen_str(self):
        return "Code generated by {}\n".format(DryDefs.PROJ_NAME)

    def get_time_gen_str(self):
        time_str = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d %H:%M:%S')
        return "Generation time: " + str(time_str)

    @abc.abstractmethod
    def generate_constant_class_code(self, dry_constant):
        pass

    @abc.abstractmethod
    def generate_enum_class_code(self, dry_constant):
        pass
