# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mcenter_server_api.models.base_model_ import Model
from mcenter_server_api import util


class DataViewIon(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pattern=None, status=None):  # noqa: E501
        """DataViewIon - a model defined in OpenAPI

        :param pattern: The pattern of this DataViewIon.  # noqa: E501
        :type pattern: MLAppProfile
        :param status: The status of this DataViewIon.  # noqa: E501
        :type status: DataViewIonStatus
        """
        self.openapi_types = {
            'pattern': 'MLAppProfile',
            'status': 'DataViewIonStatus'
        }

        self.attribute_map = {
            'pattern': 'pattern',
            'status': 'status'
        }

        self._pattern = pattern
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'DataViewIon':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataView_ion of this DataViewIon.  # noqa: E501
        :rtype: DataViewIon
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pattern(self):
        """Gets the pattern of this DataViewIon.


        :return: The pattern of this DataViewIon.
        :rtype: MLAppProfile
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern):
        """Sets the pattern of this DataViewIon.


        :param pattern: The pattern of this DataViewIon.
        :type pattern: MLAppProfile
        """

        self._pattern = pattern

    @property
    def status(self):
        """Gets the status of this DataViewIon.


        :return: The status of this DataViewIon.
        :rtype: DataViewIonStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DataViewIon.


        :param status: The status of this DataViewIon.
        :type status: DataViewIonStatus
        """

        self._status = status
