# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mcenter_server_api.models.base_model_ import Model
from mcenter_server_api import util


class MLAppProfilePipelineAgentSet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, agent_id=None, pipeline_profile_id=None):  # noqa: E501
        """MLAppProfilePipelineAgentSet - a model defined in OpenAPI

        :param agent_id: The agent_id of this MLAppProfilePipelineAgentSet.  # noqa: E501
        :type agent_id: str
        :param pipeline_profile_id: The pipeline_profile_id of this MLAppProfilePipelineAgentSet.  # noqa: E501
        :type pipeline_profile_id: str
        """
        self.openapi_types = {
            'agent_id': 'str',
            'pipeline_profile_id': 'str'
        }

        self.attribute_map = {
            'agent_id': 'agentId',
            'pipeline_profile_id': 'pipelineProfileId'
        }

        self._agent_id = agent_id
        self._pipeline_profile_id = pipeline_profile_id

    @classmethod
    def from_dict(cls, dikt) -> 'MLAppProfilePipelineAgentSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MLAppProfile_pipelineAgentSet of this MLAppProfilePipelineAgentSet.  # noqa: E501
        :rtype: MLAppProfilePipelineAgentSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def agent_id(self):
        """Gets the agent_id of this MLAppProfilePipelineAgentSet.


        :return: The agent_id of this MLAppProfilePipelineAgentSet.
        :rtype: str
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this MLAppProfilePipelineAgentSet.


        :param agent_id: The agent_id of this MLAppProfilePipelineAgentSet.
        :type agent_id: str
        """

        self._agent_id = agent_id

    @property
    def pipeline_profile_id(self):
        """Gets the pipeline_profile_id of this MLAppProfilePipelineAgentSet.


        :return: The pipeline_profile_id of this MLAppProfilePipelineAgentSet.
        :rtype: str
        """
        return self._pipeline_profile_id

    @pipeline_profile_id.setter
    def pipeline_profile_id(self, pipeline_profile_id):
        """Sets the pipeline_profile_id of this MLAppProfilePipelineAgentSet.


        :param pipeline_profile_id: The pipeline_profile_id of this MLAppProfilePipelineAgentSet.
        :type pipeline_profile_id: str
        """

        self._pipeline_profile_id = pipeline_profile_id
