# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mcenter_server_api.models.base_model_ import Model
from mcenter_server_api import util


class ModelStat(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, id=None, type=None):  # noqa: E501
        """ModelStat - a model defined in OpenAPI

        :param data: The data of this ModelStat.  # noqa: E501
        :type data: str
        :param id: The id of this ModelStat.  # noqa: E501
        :type id: str
        :param type: The type of this ModelStat.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'data': 'str',
            'id': 'str',
            'type': 'str'
        }

        self.attribute_map = {
            'data': 'data',
            'id': 'id',
            'type': 'type'
        }

        self._data = data
        self._id = id
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'ModelStat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelStat of this ModelStat.  # noqa: E501
        :rtype: ModelStat
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ModelStat.


        :return: The data of this ModelStat.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ModelStat.


        :param data: The data of this ModelStat.
        :type data: str
        """

        self._data = data

    @property
    def id(self):
        """Gets the id of this ModelStat.


        :return: The id of this ModelStat.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ModelStat.


        :param id: The id of this ModelStat.
        :type id: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this ModelStat.


        :return: The type of this ModelStat.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ModelStat.


        :param type: The type of this ModelStat.
        :type type: str
        """

        self._type = type
