# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mcenter_server_api.models.base_model_ import Model
from mcenter_server_api import util


class ModelSource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, details=None, mode=None):  # noqa: E501
        """ModelSource - a model defined in OpenAPI

        :param details: The details of this ModelSource.  # noqa: E501
        :type details: ModelSourceDetails
        :param mode: The mode of this ModelSource.  # noqa: E501
        :type mode: str
        """
        self.openapi_types = {
            'details': 'ModelSourceDetails',
            'mode': 'str'
        }

        self.attribute_map = {
            'details': 'details',
            'mode': 'mode'
        }

        self._details = details
        self._mode = mode

    @classmethod
    def from_dict(cls, dikt) -> 'ModelSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelSource of this ModelSource.  # noqa: E501
        :rtype: ModelSource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def details(self):
        """Gets the details of this ModelSource.


        :return: The details of this ModelSource.
        :rtype: ModelSourceDetails
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this ModelSource.


        :param details: The details of this ModelSource.
        :type details: ModelSourceDetails
        """

        self._details = details

    @property
    def mode(self):
        """Gets the mode of this ModelSource.


        :return: The mode of this ModelSource.
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this ModelSource.


        :param mode: The mode of this ModelSource.
        :type mode: str
        """

        self._mode = mode
