# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mcenter_server_api.models.base_model_ import Model
from mcenter_server_api import util


class RolePermissions(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, map=None):  # noqa: E501
        """RolePermissions - a model defined in OpenAPI

        :param map: The map of this RolePermissions.  # noqa: E501
        :type map: RolePermissionsMap
        """
        self.openapi_types = {
            'map': 'RolePermissionsMap'
        }

        self.attribute_map = {
            'map': 'map'
        }

        self._map = map

    @classmethod
    def from_dict(cls, dikt) -> 'RolePermissions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Role_permissions of this RolePermissions.  # noqa: E501
        :rtype: RolePermissions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def map(self):
        """Gets the map of this RolePermissions.


        :return: The map of this RolePermissions.
        :rtype: RolePermissionsMap
        """
        return self._map

    @map.setter
    def map(self, map):
        """Sets the map of this RolePermissions.


        :param map: The map of this RolePermissions.
        :type map: RolePermissionsMap
        """

        self._map = map
